name: CI

on:
  push:
    branches:
      - master
      - 'ci/**'

  pull_request:
    branches: [ master ]

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        emacs_version:
          - 27.1
          - 28.2
        ignore_warnings:
          - true
    steps:
    - uses: actions/checkout@v2
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}
    - uses: leotaku/elisp-check@master
      with:
        check: melpa
        file: 'meow.el'
        ignore_warnings: false
        warnings_as_errors: false
